export const ADD_TO_SUMMONER_LIST = 'ADD_TO_SUMMONER_LIST';
export const REMOVE_FROM_SUMMONER_LIST = 'REMOVE_FROM_SUMMONER_LIST';
export const CHANGE_SELECTED_SUMMONER = 'CHANGE_SELECTED_SUMMONER';
export const CHANGE_SELECTED_VIEW = 'CHANGE_SELECTED_VIEW';